export const NEXT_AUTH_SESSION_TOKEN = 'next-auth.session-token';
export const NEXT_AUTH_SESSION_TOKEN_SECURE = '__Secure-next-auth.session-token';
export const REF_COOKIE_NAME = 'tcl_ref';
export const SESSION_TOKEN = 'session_token';
export const QUIZ_TOKEN = 'quiz_token';
export const QUERY_PROJECT = 'project';
export const QUERY_CALLBACK = 'callback';
export const QUERY_CALLBACK_ERROR = 'callback_error';
export const QUERY_CALLBACK_SUCCESS = 'callback_success';
export const QUERY_PROJECT_ID = 'project_id';
export const QUERY_PAYMENT_PLAN_ID = 'payment_plan_id';
export const QUERY_ANNOUNCEMENT = 'announcement';
export const QUERY_EVENT = 'event';
export const QUERY_QUIZ = 'quiz';
export const QUERY_PAGE = 'page';
export const QUERY_PER_PAGE = 'per_page';
export const PER_PAGE = 25;
export const REDIS_METRICS_DATA_EXPIRATION = 15 * 24 * 60 * 60;

export const MAX_BODY_LENGTH = 209715200; //200mb
export const MAX_CONTENT_LENGTH = 209715200; //200mb
