import { z } from 'zod';

export const campaignSchema = z.object({
  name: z.string().min(2, { message: 'Campaign name is required.' }),
  project: z.string().min(2, { message: 'Please select a project.' }),
  user: z.string().email(),
  projectName: z.string(),
  enabled: z.boolean(),
  isPercentage: z.boolean(),
  isInternal: z.boolean(),
  isAgency: z.boolean(),
  isCreator: z.boolean(),
  trackMarket: z.boolean(),
  trackSocial: z.boolean(),
  startDate: z.date({ required_error: 'Please select a date and time' }),
  endDate: z.date({ required_error: 'Please select a date and time' }),
  budget: z.nullable(z.number()),
  description: z.string(),
  notes: z.string(),
  agency: z.string(),
  agencyUrl: z.string(),
  marketBudget: z.nullable(z.number()),
  socialBudget: z.nullable(z.number()),
  marketStatSnapshot: z.nullable(
    z.object({
      price: z.number(),
      marketCap: z.number(),
      volume: z.number(),
      holders: z.number(),
      buys: z.number(),
      sells: z.number(),
      twitter: z.number(),
      discord: z.number(),
      telegram: z.number(),
      priceMedian: z.number(),
      marketCapMedian: z.number(),
      volumeMedian: z.number(),
      holdersMedian: z.number(),
      buysMedian: z.number(),
      sellsMedian: z.number(),
      twitterMedian: z.number(),
      discordMedian: z.number(),
      telegramMedian: z.number(),
    }),
  ),
  priceGoal: z.nullable(z.number()),
  marketCapGoal: z.nullable(z.number()),
  volumeGoal: z.nullable(z.number()),
  holdersGoal: z.nullable(z.number()),
  twitterGoal: z.nullable(z.number()),
  discordGoal: z.nullable(z.number()),
  telegramGoal: z.nullable(z.number()),
});

export type Campaign = z.infer<typeof campaignSchema>;
