import type { NextPage } from 'next';
import Head from 'next/head';

import Hero from '../components/Hero/Hero';
import ProjectsTable from '../components/ProjectsTable/ProjectsTable';
import JoinOurCommunity from '../components/JoinOurCommunity';
import BlogPosts from '../components/BlogPosts';
import TrackVitalsDisclaimer from '../components/TrackVitalsDisclaimer';
import { getProjectsList } from '../data/getters';

const Home: NextPage = ({ projects }) => {
  console.log(projects);
  
  return (
    <div>
      <Head>
        <title>TCL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <ProjectsTable data={projects} />
        <JoinOurCommunity />
        <BlogPosts />
        <TrackVitalsDisclaimer />
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const projects = await getProjectsList();

  return {
    props: {
      projects,
    },
    revalidate: 5,
  };
};
