import type { NextPage } from 'next';
import Head from 'next/head';

import { Hero } from '../components/Hero';
import { ProjectsTable } from '../components/ProjectsTable';
import { JoinOurCommunity } from '../components/JoinOurCommunity';
import { BlogPosts } from '../components/BlogPosts';
import TrackVitalsDisclaimer from '../components/TrackVitalsDisclaimer';
import { getProjectsCount, getProjectsForHomepageList } from '../data/getters';
import { useEffect, useState } from 'react';

type HomeProps = {
  projects: [];
  projectsCount: number;
};

const Home: NextPage<HomeProps> = ({ projects, projectsCount }) => {
  const [projectData, setProjectData] = useState({ projects: [], projectsCount: 0 });

  useEffect(() => {
    setProjectData((state) => ({ ...state, projects, projectsCount }));
  }, [projects]);

  return (
    <div>
      <Head>
        <title>TCL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <ProjectsTable data={projectData.projects} projectsCount={projectData.projectsCount} />
        <JoinOurCommunity />
        <BlogPosts />
        <TrackVitalsDisclaimer />
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const projects = await getProjectsForHomepageList();
  const projectsCount = await getProjectsCount();

  return {
    props: {
      projects,
      projectsCount,
    },
    revalidate: 5,
  };
};
